# -*- coding: utf-8 -*-
"""GEN_AI_PRACTICAL_No.5_Attention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKCrVdrc0wz02_RCDTh4uugmWqvVrJR_
"""

import numpy as np

print("---Simple Attention Mechanism Explanation ---")

encoder_outputs = np.array([
    [0.1,0.2],
    [0.5,0.3],
    [0.2,0.8],
    [0.9,0.1]
])

print(f"\n Encoder Outputs (4 words, 2 features each):\n{encoder_outputs}")


decoder_hidden_state = np.array([0.7,0.4])

print(f"\n Decoder Hidden State (what we are looking for):  {decoder_hidden_state}")


alignment_score = np.dot(encoder_outputs, decoder_hidden_state)
print(f"\n Alignment Score (Similarity of each encoder output to decoder state): {alignment_score}")


def softmax(x):
  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)


attention_weights = softmax(alignment_score)

print(f"\n Attention Weight (how much to 'pay attention'to each word):{attention_weights}")

print(f"\n(Notice that the word 'student'(index 3) got a higher weight, meaning it's more releveant to 'learning')")

context_vector = np.sum(encoder_outputs * attention_weights[:, np.newaxis],axis=0)
print(f"\nContext Vector (weighted sum of encoder outputs, 'paying attention'):{context_vector}")


print("\n ---- How it works ----")