# -*- coding: utf-8 -*-
"""Gen_AI_Practical_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfvdROxvc6K5uRzunIOmhZBORCPu0nUJ
"""

!pip install gensim

# Install Gensim first:
# pip install gensim

from gensim.models import Word2Vec

# 1. Create a "Toy" Dataset
sentences = [
    ['the', 'king', 'rules', 'the', 'kingdom'],
    ['the', 'queen', 'rules', 'the', 'kingdom'],
    ['the', 'prince', 'rules', 'the', 'kingdom'],
    ['an', 'apple', 'is', 'a', 'tasty', 'fruit'],
    ['an', 'orange', 'is', 'a', 'tasty', 'fruit']
]

print("--- Training Models ---")

# 2. Train the CBOW Model
model_cbow = Word2Vec(
    sentences,
    vector_size=10,
    window=2,
    min_count=1,
    sg=0,
    epochs=100
)

print("CBOW model trained successfully.")

# 3. Train the Skip-gram Model
model_skipgram = Word2Vec(
    sentences,
    vector_size=10,
    window=2,
    min_count=1,
    sg=1,
    epochs=100
)

print("Skip-gram model trained successfully.\n")


# 4. Compare Semantic Similarities
def test_similarities(model, model_name):

    print(f"--- Semantic Similarities using {model_name} ---")

    # Similarity between queen and king
    sim_royal = model.wv.similarity('queen', 'king')
    print(f"Similarity ('queen', 'king'): {sim_royal:.4f}")

    # Similarity between apple and is
    sim_fruit = model.wv.similarity('apple', 'is')
    print(f"Similarity ('apple', 'is'): {sim_fruit:.4f}")

    # Similarity between unrelated words
    sim_unrelated = model.wv.similarity('queen', 'apple')
    print(f"Similarity ('queen', 'apple'): {sim_unrelated:.4f}")

    print("-" * 40)


# Test CBOW
test_similarities(model_cbow, "CBOW")

# Test Skip-gram
test_similarities(model_skipgram, "Skip-gram")

!pip install gensim --quiet

import gensim
from gensim.models import KeyedVectors
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

print("Gensim version:", gensim.__version__)

import gensim.downloader as api

# Load pre-trained Word2Vec model
model = api.load("word2vec-google-news-300")

# Find words most similar to "google"
print(model.most_similar("google"))

word_to_visualize = [
    'king','queen','man','women',
    'apple','banana','orange','fruit',
    'car','truck','vehicle','road',
    'happy','sad','angry','emotion'
]

filtered_words = [word for word in word_to_visualize if word in model.key_to_index]
vectors = [model[word] for word in filtered_words]

pca = PCA(n_components=2)
vectors_2d = pca.fit_transform(vectors)


plt.figure(figsize=(12, 10))
plt.scatter(vectors_2d[:, 0], vectors_2d[:, 1],edgecolors='k',c='skyblue')

for i, word in enumerate(filtered_words):
    plt.annotate(word, (vectors_2d[i, 0], vectors_2d[i, 1]),textcoords="offset points",xytext=(5, 5),ha='center')

plt.title("Word Embeddings Visualization")
plt.xlabel("Dimension 1")
plt.ylabel("Dimension 2")
plt.grid(True)
plt.show()