# -*- coding: utf-8 -*-
"""Gen_AI_Practical_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-6cOAMxMWAZgIJVRooeiS3FT7NicAgU
"""

import numpy as np
from tensorflow.keras.layers import Input, LSTM, Dense

num_samples = 1000
input_seq_len = 10
num_features = 5
target_seq_len = input_seq_len # Define target_seq_len

encoder_input_data = np.random.randint(0,num_features,size=(num_samples,input_seq_len))
decoder_target_data = np.zeros((num_samples,target_seq_len, num_features),dtype='float32')
decoder_input_data = np.zeros((num_samples, target_seq_len, num_features),dtype='float32')


encoder_input_one_hot = np.zeros((num_samples, input_seq_len, num_features),dtype='float32')
for i, seq_data in enumerate(encoder_input_data): # Renamed Sequence to seq_data
    for t, feature in enumerate(seq_data): # Renamed Sequence to seq_data
        encoder_input_one_hot[i, t, feature] = 1.0


for sample_idx in range(num_samples): # Changed loop variable from i to sample_idx
    reversed_sequence = encoder_input_data[sample_idx][::-1] # Use sample_idx

    # Decoder input: special start token at index 0, then shifted reversed sequence
    # Assuming feature 0 is a special 'start' token
    decoder_input_data[sample_idx, 0, 0] = 1.0
    for t_idx, feature_val in enumerate(reversed_sequence): # Iterate over full sequence
        if t_idx < target_seq_len - 1: # Ensure we don't exceed target_seq_len for shifted input
            decoder_input_data[sample_idx, t_idx + 1, feature_val] = 1.0 # Shifted by 1

    # Decoder target: The reversed sequence
    for t_idx, feature_val in enumerate(reversed_sequence): # Use new variables t_idx, feature_val
        if t_idx < target_seq_len: # Ensure we don't exceed target_seq_len
            decoder_target_data[sample_idx, t_idx, feature_val] = 1.0

print("Encoder Input Shape:",encoder_input_one_hot.shape)
print("Decoder Input Shape:",decoder_input_data.shape)
print("Decoder Target Shape:",decoder_target_data.shape)

print("\nSimple Encoder Input (indices):")
print(encoder_input_data[:5])
print("\nSimple Decoder Target (one-hot , indicating indices):")
print((np.argmax(decoder_target_data[0],axis=-1))) # Added missing parenthesis

#Encoder setup
latent_dim =256

encoder_inputs = Input(shape=(None, num_features))
encoder_lstm = LSTM(latent_dim, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)
#we discard encoder outputs and only keep the states.
encoder_states = [state_h, state_c]

from numpy._core.strings import decode

#Decoder setup
decoder_inputs = Input(shape=(None, num_features))
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)
decoder_dense = Dense(num_features, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

from tensorflow.keras.models import Model

# Define the model that will turn
# encoder_input_data & decoder_input_data  into decordwer_target_data


model = Model((encoder_inputs, decoder_inputs), decoder_outputs)

model.summary()